### ISSUE TITLE
Does not work with Pester 5.x

### ISSUE THREAD

**Issue by KitKat31337** [ironmansoftware/poshtools-docs#12]
The -TestName parameter was removed and the test explorer no longer runs the tests correctly.

See https://github.com/pester/Pester/issues/1479

**Comment by Veretax** [comment]
Yeah, I can confirm I ran into this today.   Is there a preferred way to run these in visual studio now?  Or do we need to revert to Powershell ISE?

**Comment by KitKat31337** [comment]
I reverted to Pester 4

**Comment by adamdriscoll** [comment]
We have implemented Pester v5 support in 2021.11.0
