### ISSUE TITLE
Documentation: Problem with the Readme

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/poshtools-docs#18]
1. Some formatting issues in the line that mentions "To purchase a license" (pictured below)

![image](https://user-images.githubusercontent.com/537287/148824083-39a6869a-ad95-426c-8114-93b7fb85f6d9.png)

2. Three of the features are missing check marks (Project System, Debugging and Tools)

**Comment by adamdriscoll** [comment]
1. That's a GitBook feature. You can see the result here: https://docs.poshtools.com/
2. Those are sections and not individual features. I noticed that editor had checks though when it shouldn't. It's most clear on the gitbook page
