### ISSUE TITLE
Documentation: Clarify supported PowerShell versions

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/poshtools-docs#19]
### Problem
```
The current PowerShell requirement is listed as 5.x but this seems a bit outdated for 2022
```

### Suggested Solution
```
Specifically enumerate the supported versions as Microsoft does on their documentation. Pictured below.
```

### Media

![image](https://user-images.githubusercontent.com/537287/148825062-1fa1ec00-23c4-4b2a-9674-21032627a305.png)

### Reference
[https://docs.poshtools.com/system-requirements](https://docs.poshtools.com/system-requirements)

**Comment by DataTraveler1** [comment]
By "outdated" I mean any reference that could be construed as 5.0 or 6.x.

**Comment by DataTraveler1** [comment]
The following page also has references to PowerShell versions that might need to be updated [https://docs.poshtools.com/powershell-tools-documentation/powershell-support](https://docs.poshtools.com/powershell-tools-documentation/powershell-support)

**Comment by adamdriscoll** [comment]
Thanks! Updated
