### ISSUE TITLE
Update: Location of Interactive Window

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/poshtools-docs#20]
## Current content

To access the PowerShell interactive window, click View->**Other Windows**->PowerShell Interactive Window. You can also use the default key combination Ctrl+Shift+.

## Suggested new content

To access the PowerShell interactive window, click View->**PowerShell**->PowerShell Interactive Window. You can also use the default key combination **Ctrl+Shift+\\**.

## Explanation
```
The PowerShell Pro Tools commands have been moved from 'Other Windows'. Also the shortcut is missing the backslash.
```

## Source
```
https://docs.poshtools.com/powershell-tools-documentation/powershell-interactive-window
```

## Extra

![image](https://user-images.githubusercontent.com/537287/149638891-fb40ce8e-3a56-4766-b82e-217275166c31.png)

**Comment by adamdriscoll** [comment]
Fixed!
