### ISSUE TITLE
Remove or update: "Project System"

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/poshtools-docs#21]
## Current content

> - Build Events
> - Enabling MSBuild Support for VS2015
> - Upgrading a PowerShell Project to use June Release MSBuild Tasks
> 

## Suggested new content

If it is no longer needed, kindly consider excising this content ✂️

## Explanation
```
Users have since upgraded from VS2015
```

## Source
```
https://docs.poshtools.com/powershell-tools-documentation/project-system
```

## Extra

_none_

**Comment by adamdriscoll** [comment]
I've removed some pages and added a few more.
