### ISSUE TITLE
Update: Screenshot of Settings -> Analysis

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/poshtools-docs#22]
## Outdated content

![image](https://user-images.githubusercontent.com/537287/149642027-98b2ec40-0448-43c4-8170-f7d0156728cf.png)

## Updated content

![image](https://user-images.githubusercontent.com/537287/149642039-7f6bdcee-76f0-4cc6-89cd-e269f884a03b.png)

## Explanation
```
The Analysis window has changed in appearance
```

## Source
```
https://docs.poshtools.com/powershell-tools-documentation/settings/analysis
```

## Extra

_none_

**Comment by adamdriscoll** [comment]
Updated. Thanks!
